SELECT C.ID AS CUSTOMER_ID,
       C.NAME AS CUSTOMER_NAME,
       SO.ITEM_ID,
       AVG(SO.AMOUNT / SO.QUANTITY) AS AVERAGE_PRICE
FROM CUSTOMER C
JOIN SALES_ORDER SO ON C.ID = SO.CUSTOMER_ID
GROUP BY C.ID,
         C.NAME,
         SO.ITEM_ID;