name: Build Gradle project

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install newman
        run: npm install -g newman

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0

      - name: Run build with Gradle Wrapper
        run: ./gradlew build
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379

      - name: Run api-genshin-impact in the background
        run: |
          ./gradlew :api-genshin-impact:bootRun --args='--spring.profiles.active=local-h2' &
          echo $! > genshin-impact.pid

      - name: Wait for api-genshin-impact to start
        run: sleep 15
        shell: bash

      - name: Run newman for api-genshin-impact
        run: newman run ./api-genshin-impact/newman/api-genshin-impact.postman_collection.json -e ./api-genshin-impact/newman/api-genshin-impact-local.postman_environment.json

      - name: Shut down api-genshin-impact
        run: |
          if [ -f genshin-impact.pid ]; then
            kill $(cat genshin-impact.pid) || echo "Process already terminated"
            rm genshin-impact.pid
          fi

      - name: Run api-honkai-star-rail in the background
        run: |
          ./gradlew :api-honkai-star-rail:bootRun --args='--spring.profiles.active=local-h2' &
          echo $! > honkai-star-rail.pid

      - name: Wait for api-honkai-star-rail to start
        run: sleep 15
        shell: bash

      - name: Run newman for api-honkai-star-rail
        run: newman run ./api-honkai-star-rail/newman/api-honkai-star-rail.postman_collection.json -e ./api-honkai-star-rail/newman/api-honkai-star-rail-local.postman_environment.json

      - name: Shut down api-honkai-star-rail
        run: |
          if [ -f honkai-star-rail.pid ]; then
            kill $(cat honkai-star-rail.pid) || echo "Process already terminated"
            rm honkai-star-rail.pid
          fi

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@cc4fc85e6b35bafd578d5ffbc76a5518407e1af0
