name: Build Gradle project

on: [ push, pull_request ]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install newman
        run: npm install -g newman

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.0

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Run bootRun in the background
        run: ./gradlew :api-genshin-impact:bootRun --args='--spring.profiles.active=local-h2' &

      - name: Run newman
        run: newman run ./api-genshin-impact/newman/demo-genshin-impact-spring-boot.postman_collection.json -e ./api-genshin-impact/newman/demo-genshin-impact-spring-boot-local.postman_environment.json
