name: Build Gradle project

on: [ push, pull_request ]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install newman
        run: npm install -g newman

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.0

      - name: Run build with Gradle Wrapper
        run: ./gradlew build
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379

      - name: Run api-genshin-impact in the background
        run: ./gradlew :api-genshin-impact:bootRun --args='--spring.profiles.active=local-h2' &

      - name: Wait for api-genshin-impact to start
        run: sleep 10
        shell: bash

      - name: Run newman for api-genshin-impact
        run: newman run ./api-genshin-impact/newman/api-genshin-impact.postman_collection.json -e ./api-genshin-impact/newman/api-genshin-impact-local.postman_environment.json

      - name: Run api-honkai-star-rail in the background
        run: ./gradlew :api-honkai-star-rail:bootRun --args='--spring.profiles.active=local-h2' &

      - name: Wait for api-honkai-star-rail to start
        run: sleep 10
        shell: bash

      - name: Run newman for api-honkai-star-rail
        run: newman run ./api-honkai-star-rail/newman/api-honkai-star-rail.postman_collection.json -e ./api-honkai-star-rail/newman/api-honkai-star-rail-local.postman_environment.json
